library(tidyverse)
table<-read.csv("~/network/X/Labs/Blaser/share/collaborators/lapalombella_pu_network/differentially expressed genes/20220322-genes.LCK.LK.p53.TET2.all.new.csv")
head(table)
ans_TET2BM<-subset(table, Gen == "TET2" & threshold == "TRUE" & Cell == "BM")
nrow(ans_TET2BM)
ans_TET2SPN<-subset(table, Gen == "TET2" & threshold == "TRUE" & Cell == "Spleen")
nrow(ans_TET2SPN)
ans_TP53BM<-subset(table, Gen == "TP53" & threshold == "TRUE" & Cell == "BM")
nrow(ans_TP53BM)
ans_TP53SPN<-subset(table, Gen == "TP53" & threshold == "TRUE" & Cell == "Spleen")
nrow(ans_TP53SPN)
ans_TP53TET2BM<-subset(table, Gen == "TP53.TET2" & threshold == "TRUE" & Cell == "BM")
nrow(ans_TP53TET2BM)
ans_TP53TET2SPN<-subset(table, Gen == "TP53.TET2" & threshold == "TRUE" & Cell == "Spleen")
nrow(ans_TP53TET2SPN)
